### ISSUE TITLE
SQL Associate Practical Exam SQ501P

### ISSUE THREAD

**Issue by Spoutnikrs** [christyleeyx/sql-associate-cert#1]
Hey there! I hope you're doing great! I'm trying to reach out to you regarding the SQL Associate Certification. I could really use some help with the project, especially with the initial checkpoint. I've been making progress on other tasks, but I'm stuck on the first checkpoint. I've tried looking for solutions online and in the documentation, but haven't had any luck. I would really appreciate it if you could lend a hand. Thanks a lot!

![image](https://github.com/christyleeyx/sql-associate-cert/assets/93091566/0e40ca01-8018-4871-8bce-31e1b1a15906)

**Comment by christyleeyx** [comment]
hi! if you did use my notebook(3) which is the latest submission, i did alter one part of my code for task 3 which caused the error. 

SELECT
    s.description,
    b.id AS branch_id,
    ...
is the correct code, i previously gave an alias for s.description and hence did not fulfil the required column name, 
hope this helps.

**Comment by Spoutnikrs** [comment]
Thanks for your feedback. I'll keep it in mind for next time as I have to wait 10 days before trying again. Thanks for your help!
